package org.jboss.qa.hornetq.test.prepares;

public class PrepareParams {

    public static final String MAX_SIZE_BYTES = "MAX_SIZE_BYTES";

    public static final String MAX_DELIVERY_ATTEMPTS = "MAX_DELIVERY_ATTEMPTS";

    public static final String PAGE_SIZE_BYTES = "PAGE_SIZE_BYTES";

    public static final String ADDRESS = "ADDRESS";

    public static final String ADDRESS_FULL_POLICY = "ADDRESS_FULL_POLICY";

    public static final String REDELIVERY_DELAY = "REDELIVERY_DELAY";

    public static final String REDISTRIBUTION_DELAY = "REDISTRIBUTION_DELAY";

    public static final String LAST_VALUE_QUEUE =  "LAST_VALUE_QUEUE";

    public static final String EXPIRY_QUEUE =  "EXPIRY_QUEUE";

    public static final String DEAD_LETTER_QUEUE =  "DEAD_LETTER_QUEUE";

    public static final String DESTINATION_COUNT =  "DESTINATION_COUNT";

    public static final String DISABLE_TRACE_LOGGING =  "DISABLE_TRACE_LOGGING";

    public static final String ENABLE_SECURITY =  "ENABLE_SECURITY";

    public static final String QOS =  "QOS";

    public static final String RECONNECT_ATTEMPTS =  "RECONNECT_ATTEMPTS";

    public static final String INVM_CONNECTION_FACTORY_TYPE =  "INVM_CONNECTION_FACTORY_TYPE";

    public static final String REMOTE_CONNECTION_FACTORY_HA =  "REMOTE_CONNECTION_FACTORY_HA";

    public static final String REMOTE_CONNECTION_FACTORY_BLOCK_ON_ACK =  "REMOTE_CONNECTION_FACTORY_BLOCK_ON_ACK";

    public static final String REMOTE_CONNECTION_FACTORY_RETRY_INTERVAL =  "REMOTE_CONNECTION_FACTORY_RETRY_INTERVAL";

    public static final String REMOTE_CONNECTION_FACTORY_RETRY_INTERVAL_MULTIPLIER =  "REMOTE_CONNECTION_FACTORY_RETRY_INTERVAL_MULTIPLIER";

    public static final String REMOTE_CONNECTION_FACTORY_RECONNECT_ATTEMPTS =  "REMOTE_CONNECTION_FACTORY_RECONNECT_ATTEMPTS";

    public static final String REMOTE_CONNECTION_FACTORY_COMPRESSION =  "REMOTE_CONNECTION_FACTORY_COMPRESSION";

    public static final String REMOTE_CONNECTION_FACTORY_MIN_LARGE_MESSAGE_SIZE =  "REMOTE_CONNECTION_FACTORY_MIN_LARGE_MESSAGE_SIZE";

    public static final String REMOTE_CONNECTION_FACTORY_TYPE =  "REMOTE_CONNECTION_FACTORY_TYPE";

    public static final String POOLED_CONNECTION_FACTORY_HA =  "POOLED_CONNECTION_FACTORY_HA";

    public static final String POOLED_CONNECTION_FACTORY_BLOCK_ON_ACK =  "POOLED_CONNECTION_FACTORY_BLOCK_ON_ACK";

    public static final String POOLED_CONNECTION_FACTORY_RETRY_INTERVAL =  "POOLED_CONNECTION_FACTORY_RETRY_INTERVAL";

    public static final String POOLED_CONNECTION_FACTORY_RETRY_INTERVAL_MULTIPLIER =  "POOLED_CONNECTION_FACTORY_RETRY_INTERVAL_MULTIPLIER";

    public static final String POOLED_CONNECTION_FACTORY_RECONNECT_ATTEMPTS =  "POOLED_CONNECTION_FACTORY_RECONNECT_ATTEMPTS";

    public static final String POOLED_CONNECTION_FACTORY_MIN_POOL_SIZE =  "POOLED_CONNECTION_FACTORY_MIN_POOL_SIZE";

    public static final String POOLED_CONNECTION_FACTORY_MAX_POOL_SIZE =  "POOLED_CONNECTION_FACTORY_MAX_POOL_SIZE";

    public static final String POOLED_CONNECTION_FACTORY_MIN_LARGE_MESSAGE_SIZE =  "POOLED_CONNECTION_FACTORY_MIN_LARGE_MESSAGE_SIZE";

    public static final String PREPARE_DESTINATIONS =  "PREPARE_DESTINATIONS";

    public static final String PREPARE_QUEUE =  "PREPARE_QUEUE";

    public static final String PREPARE_TOPIC =  "PREPARE_TOPIC";

    public static final String PREPARE_IN_QUEUE =  "PREPARE_IN_QUEUE";

    public static final String PREPARE_IN_TOPIC =  "PREPARE_IN_TOPIC";

    public static final String PREPARE_OUT_QUEUE =  "PREPARE_OUT_QUEUE";

    public static final String PREPARE_OUT_TOPIC =  "PREPARE_OUT_TOPIC";

    public static final String JMS_BRIDGE_FAILURE_RETRY_INTERVAL =  "JMS_BRIDGE_FAILURE_RETRY_INTERVAL";

    public static final String JMS_BRIDGE_MAX_BATCH_SIZE =  "JMS_BRIDGE_MAX_BATCH_SIZE";

    public static final String JMS_BRIDGE_MAX_BATCH_TIME =  "JMS_BRIDGE_MAX_BATCH_TIME";

    public static final String JMS_BRIDGE_ADD_MESSAGE_ID_IN_HEADER =  "JMS_BRIDGE_ADD_MESSAGE_ID_IN_HEADER";

    public static final String JMS_BRIDGE_MAX_RETRIES =  "JMS_BRIDGE_MAX_RETRIES";

    public static final String CONNECTOR_TYPE = "CONNECTOR_TYPE";

    public static final String CLUSTER_TYPE = "CLUSTER_TYPE";

    public static final String JOURNAL_TYPE = "JOURNAL_TYPE";

    public static final String JOURNAL_FILE_SIZE = "JOURNAL_FILE_SIZE";

    public static final String CLUSTER_CONNECTION_CALL_TIMEOUT = "CLUSTER_CONNECTION_CALL_TIMEOUT";

    public static final String CLUSTER_CONNECTION_CHECK_PERIOD = "CLUSTER_CONNECTION_CHECK_PERIOD";

    public static final String CLUSTER_CONNECTION_TTL = "CLUSTER_CONNECTION_TTL";

    public static final String SECURITY_GUEST_CREATE_DURABLE_QUEUE = "SECURITY_GUEST_CREATE_DURABLE_QUEUE";

    public static final String SECURITY_GUEST_CREATE_NON_DURABLE_QUEUE = "SECURITY_GUEST_CREATE_NON_DURABLE_QUEUE";

    public static final String SECURITY_GUEST_DELETE_DURABLE_QUEUE = "SECURITY_GUEST_DELETE_DURABLE_QUEUE";

    public static final String SECURITY_GUEST_DELETE_NON_DURABLE_QUEUE = "SECURITY_GUEST_DELETE_NON_DURABLE_QUEUE";

    public static final String SECURITY_GUEST_MANAGE = "SECURITY_GUEST_MANAGE";

    public static final String SECURITY_GUEST_SEND = "SECURITY_GUEST_SEND";

    public static final String SECURITY_GUEST_CONSUME = "SECURITY_GUEST_CONSUME";

    public static final String SECURITY_ADMIN_CREATE_DURABLE_QUEUE = "SECURITY_ADMIN_CREATE_DURABLE_QUEUE";

    public static final String SECURITY_ADMIN_CREATE_NON_DURABLE_QUEUE = "SECURITY_ADMIN_CREATE_NON_DURABLE_QUEUE";

    public static final String SECURITY_ADMIN_DELETE_DURABLE_QUEUE = "SECURITY_ADMIN_DELETE_DURABLE_QUEUE";

    public static final String SECURITY_ADMIN_DELETE_NON_DURABLE_QUEUE = "SECURITY_ADMIN_DELETE_NON_DURABLE_QUEUE";

    public static final String SECURITY_ADMIN_MANAGE = "SECURITY_ADMIN_MANAGE";

    public static final String SECURITY_ADMIN_SEND = "SECURITY_ADMIN_SEND";

    public static final String SECURITY_ADMIN_CONSUME = "SECURITY_ADMIN_CONSUME";

    public static final String SECURITY_USERS_CREATE_DURABLE_QUEUE = "SECURITY_USERS_CREATE_DURABLE_QUEUE";

    public static final String SECURITY_USERS_CREATE_NON_DURABLE_QUEUE = "SECURITY_USERS_CREATE_NON_DURABLE_QUEUE";

    public static final String SECURITY_USERS_DELETE_DURABLE_QUEUE = "SECURITY_USERS_DELETE_DURABLE_QUEUE";

    public static final String SECURITY_USERS_DELETE_NON_DURABLE_QUEUE = "SECURITY_USERS_DELETE_NON_DURABLE_QUEUE";

    public static final String SECURITY_USERS_MANAGE = "SECURITY_USERS_MANAGE";

    public static final String SECURITY_USERS_SEND = "SECURITY_USERS_SEND";

    public static final String SECURITY_USERS_CONSUME = "SECURITY_USERS_CONSUME";

    public static final String TRANSACTION_TIMEOUT = "TRANSACTION_TIMEOUT";

    public static final String MAX_SAVED_REPLICATED_JOURNAL_SIZE = "MAX_SAVED_REPLICATED_JOURNAL_SIZE";

    public static final String SLOW_CONSUMER_POLICY = "SLOW_CONSUMER_POLICY";

    public static final String SLOW_CONSUMER_POLICY_THRESHOLD = "SLOW_CONSUMER_POLICY_THRESHOLD";

    public static final String SLOW_CONSUMER_POLICY_CHECK_PERIOD = "SLOW_CONSUMER_POLICY_CHECK_PERIOD";

    public static final String JMX_MANAGEMENT_ENABLED = "JMX_MANAGEMENT_ENABLED";

    public static final String FORWARD_WHEN_NO_CONSUMER = "FORWARD_WHEN_NO_CONSUMER";

    public static final String AUTO_CREATE_JMS_QUEUES = "AUTO_CREATE_JMS_QUEUES";

    public static final String AUTO_DELETE_JMS_QUEUES = "AUTO_DELETE_JMS_QUEUES";

    public static final String DATABASE = "DATABASE";

    public static final String JOURNAL_BINDINGS_TABLE = "JOURNAL_BINDINGS_TABLE";

    public static final String JOURNAL_MESSAGES_TABLE = "JOURNAL_MESSAGES_TABLE";

    public static final String JOURNAL_LARGE_MESSAGES_TABLE = "JOURNAL_LARGE_MESSAGES_TABLE";

    public static final String JOURNALS_DIRECTORY = "JOURNALS_DIRECTORY";

    public static final String REPLICATION_GROUP_NAME = "REPLICATION_GROUP_NAME";

    public static final String PREPARE_COLOCATED_BACKUP = "PREPARE_COLOCATED_BACKUP";

    public static final String HA_TYPE = "HA_TYPE";
}
